### ISSUE TITLE
Refactor the "genomic variant calling workflow" intro

### ISSUE THREAD

**Issue by mptrsen** [cmeesters/snakemake-hpc-teaching-material#14]
https://github.com/cmeesters/snakemake-hpc-teaching-material/blob/a40c30a8c9095342efcd69f2056cae8d346c1fe1/slides/creators/Getting_Started.tex#L39

Make it more easily digestible for non-biologists

**Comment by cmeesters** [comment]
@mptrsen now, there is basically just one slide left with the intro of the biological background for the creator's part: the bad figure slide. Will you give replacing the figure a go? Or shall we ask around?

**Comment by mptrsen** [comment]
Let's use this one. It's from ["Cloud computing for next-generation sequencing data analysis" (2016)](https://www.intechopen.com/chapters/53334). It's CC BY, so I added attribution and a link.

Would that be ok?

**Comment by cmeesters** [comment]
considered closed as to PR #70
