### ISSUE TITLE
Remove navigation buttons

### ISSUE THREAD

**Issue by mptrsen** [cmeesters/snakemake-hpc-teaching-material#22]
Remove the nav buttons that nobody uses.

In the preamble:

    \setbeamertemplate{navigation symbols}{}

**Comment by cmeesters** [comment]
Is this really an issue? I sometimes use them ...

Yet, it would give us some more space at the bottom.

**Comment by mptrsen** [comment]
If you actually use them, we can keep them of course. They are sometimes overlapped by boxes and I find them distracting, but that's personal preference. Perhaps a point for the config?

**Comment by cmeesters** [comment]
Na, I understand your point. They aren't strictly necessary, either. As said, I _sometimes_ use them, only. In time, when the material is more mature, jumping does not happen too often. I will just merge. 

A prolonged lunch breaks works wonders to get your mind around.
