### ISSUE TITLE
Decide on British English or American English

### ISSUE THREAD

**Issue by mptrsen** [cmeesters/snakemake-hpc-teaching-material#24]
For example "Honour" vs. "Honor" (slide 2), "standardized" vs "standardised" (slide 10, Snakemake catalogue (actually: "catalogue" vs "catalog"))

**Comment by cmeesters** [comment]
Good one. I vote for British and for standardization (sic!). Opinions?

**Comment by mptrsen** [comment]
Standarsidation and BE as well.
