### ISSUE TITLE
Unify preambles for the different slidesets

### ISSUE THREAD

**Issue by mptrsen** [cmeesters/snakemake-hpc-teaching-material#25]
We don't want to keep them all synchronised, and the layout, general settings, `\newcommand`s will be the same anyway.

I propose:

1. Create a `preamble.tex` to contain stuff that is the same in all slidesets
2. `\include` that in `Snakemake_HPC_Users.tex` and `Snakemake_HPC_Creators.tex`

**Comment by cmeesters** [comment]
Jolly good idea!

Would you like to go ahead? Else, assign this issue to me, please. I will look at it as time allows.
