### ISSUE TITLE
No licence!

### ISSUE THREAD

**Issue by cmeesters** [cmeesters/snakemake-hpc-teaching-material#41]
To distribute, we need a licence! I propose CC BY 4.0 as this is non-code material mostly. However, this requires a consensus.

Opinions?

**Comment by mptrsen** [comment]
+1 CC BY!

**Comment by cmeesters** [comment]
Stupid me: I did not mean CC-BY, but CC-BY-SA. The share alike (SA) version binds the adapter to the terms of the original licence. Any adapted versions must therefore be shared under CC BY-SA or a compatible licence. Any derived licence must be compatible. Hence: CC-BY-SA.

Opinions?

**Comment by mptrsen** [comment]
> I did not mean CC-BY, but CC-BY-SA. The share alike (SA) version binds the adapter to the terms of the original licence. Any adapted versions must therefore be shared under CC BY-SA or a compatible licence. Any derived licence must be compatible. Hence: CC-BY-SA.

If I understand correctly, that would mean that adapters have to publish their adaptation likewise, on Github or wherever. Is that realistic? (Or correct me if I misunderstood)

**Comment by cmeesters** [comment]
No, it merely means that adapters may use the material as under CC-BY, but are required to offer derived versions (if any) with the same (or compatible licence). It is a guarantee to keep all derived versions source public. 

Both models allow to download and adapt for personal needs, nothing requires publishing. (It is fine to adapt for personal use, e.g. teaching, and not to share the code. As soon as anyone wants to share, the licensing considerations from above apply.)

See https://meta.wikimedia.org/wiki/Open_Content_-_A_Practical_Guide_to_Using_Creative_Commons_Licences/The_Creative_Commons_licencing_scheme

**Comment by lukashellmann** [comment]
CC-BY-SA is fine, although I also do not mind going with just CC-BY

**Comment by mptrsen** [comment]
+1 CC-BY-SA!

**Comment by brand-fabian** [comment]
I also think both are fine, CC-BY-SA is probably a littler better.

**Comment by cmeesters** [comment]
ok, took the liberty to add a licence file and badge and create a PR #43 whilst assigning @lukashellmann (as a finger exercise)
