### ISSUE TITLE
coding wrappers

### ISSUE THREAD

**Issue by cmeesters** [cmeesters/snakemake-hpc-teaching-material#44]
new section on how to code wrappers, assigned to @brand-fabian according to meeting notes from 2023-11-10

**Comment by cmeesters** [comment]
also see issue #18

**Comment by brand-fabian** [comment]
I have added a first version of slides explaining how to use and create wrappers on the linked branch. It would be great if you could provide some feedback, whether this is the right direction, what is missing, etc.

Next I would get to fixing the alignment of the code blocks and adding some images and more examples in general.

**Comment by cmeesters** [comment]
Looks good at first glance. 2.5 points:

1. The `common` section might merit a how-to-install-wrappers slide, resp. the note that snakemake will take care and that you can point to a directory, alternatively.
2. be aware that when using `onlyenv` a handout will only contain the last slide. 
3. please use `\texttt{Snakemake}` for the project and `\altverb{snakemake}` , respectively. The first looks ugly and is subject to change (see #49). Using coherent commands will make a subsequent layout change easy.

**Comment by brand-fabian** [comment]
Thanks for the remarks, didnt know about 2 & 3 and will take a look at how I can fix this. Also I agree to the first point, maybe adding a slide in general about the different ways of addressing wrappers (file, default repository, own repositories...).

**Comment by cmeesters** [comment]
oh, I totally forgot! Could you please do a PR? We should polish and merge a.s.a.p.. Thank you!

**Comment by cmeesters** [comment]
done the PR #67 . see there.

**Comment by cmeesters** [comment]
done, for PR is done
