### ISSUE TITLE
Snakemake logo on title page and improve Snakemake typesetting 

### ISSUE THREAD

**Issue by cmeesters** [cmeesters/snakemake-hpc-teaching-material#49]
Currently, Snakemake is typeset as `\texttt{Snakemake}` over and over again. This goes along with the philosophy of having projects set in true type fonts. (program invocations are set as verbatim - this should not be confused)

However, the logo itself should be part of the title page and Snakemake overall displayed nicer.

**Comment by mptrsen** [comment]
looks resolved?

**Comment by cmeesters** [comment]
merged and done
