### ISSUE TITLE
Designing a Question List for teaching

### ISSUE THREAD

**Issue by cmeesters** [cmeesters/snakemake-hpc-teaching-material#51]
When teaching "elsewhere" a number of questions need answering.

We should have a Document to tick off those questions:

- How does the course room look like?
  - How many seats?
  - Presenter PC?
  - Possible to plug in Laptop?
  - HDMI?
  - projector situation?
  - Adaptor Needed?
  - Participant PC OS?
  - Software to log in? (putty, mobaxterm, powershell or plain ssh via Linux)
  - 2FA setup in place?
  - ssh-keys - are they to be prepared? 
  - course accounts?
  - possibility to do paired programming
- Cluster?
  - shared file space for the setup to be copied to?
  - editor choices?
  - SLURM reservation?
  - number of days?
  - colleagues who want to be trained as trainers?
 

Is there anything else you can think of? @all

**Comment by brand-fabian** [comment]
This sounds very reasonable to me. In earlier complex courses I held, it was very advantageous to provide a common workspace for all participants that can be pre setup by the teachers and accessed via Web Browser (e.g. AWS Cloud9). In this way many of the difficult parts, especially for Linux or HPC beginners, can be prepared s.t. minimal time is lost establishing an SSH connection for example.

By now I think many clusters provide some interactive form to access their resources via e.g. JupyterHub or OOD which might be a good starting point for us to layout an example setup for the teachers.

**Comment by cmeesters** [comment]
Hm, good points. I confess to be old school: The course is intended for HPC users resp. creators on HPC platforms. While I would resort to "clone from github" if there is no shared file space, I am very hesitant to start with working in Jupyter.

OOD to provide terminal access is nice to have, should be on the question list! Also, whether a work space is required and how it is set up on different clusters needs to be inquired. (Although the amount of space required for the course is minimal.)
